[versions]
accompanist = "0.25.1"
activity-compose = "1.5.1"
agp = "7.2.2"
app-compat = "1.5.1"
compose = "1.2.1"
compose-material3 = "1.0.0-beta02"
compose-preferences = "0.1.4"
compose-rules = "0.0.10"
core-ktx = "1.9.0"
coroutines = "1.6.4"
dagger-hilt = "2.43.2"
dagger-hilt-extensions = "1.0.0"
dagger-hilt-navigation-compose = "1.0.0"
dagger-hilt-vm-compiler = "1.0.0"
detekt = "1.21.0"
kotlin = "1.7.10"
kotlinter = "3.12.0"
leakcanary = "2.9.1"
lifecycle = "2.5.1"
material = "1.6.1"
navigation_compose = "2.5.2"
orbit = "4.3.2"
spotless = "6.10.0"
timber = "5.0.1"
versions = "0.42.0"

[libraries]
accompanist-navigation_animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-system-ui-controller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
app-compat = { module = "androidx.appcompat:appcompat", version.ref = "app-compat" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-rules = { module = "com.twitter.compose.rules:ktlint", version.ref = "compose-rules" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger-hilt" }
dagger-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "dagger-hilt-extensions" }
dagger-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "dagger-hilt-navigation-compose" }
dagger-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "dagger-hilt-extensions" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
navigation_compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation_compose" }
orbit-compose = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbit" }
orbit-vm = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbit" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[bundles]
classpath = [
    "compose-rules"
]
implementation = [
    "accompanist-navigation_animation",
    "accompanist-system-ui-controller",
    "activity-compose",
    "app-compat",
    "compose-animation",
    "compose-material3",
    "compose-ui",
    "compose-ui-tooling",
    "core-ktx",
    "coroutines-android",
    "dagger-hilt-android",
    "dagger-hilt-navigation-compose",
    "kotlin-stdlib",
    "lifecycle-runtime-ktx",
    "material",
    "material-icons-extended",
    "navigation_compose",
    "orbit-compose",
    "orbit-vm",
    "timber"
]
kapt = [
    "dagger-hilt-android-compiler",
    "dagger-hilt-compiler"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
